# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import models_pb2 as models__pb2


class ServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Get = channel.unary_unary(
        '/Service/Get',
        request_serializer=models__pb2.inputService.SerializeToString,
        response_deserializer=models__pb2.streams.FromString,
        )


class ServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Get(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Get': grpc.unary_unary_rpc_method_handler(
          servicer.Get,
          request_deserializer=models__pb2.inputService.FromString,
          response_serializer=models__pb2.streams.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Service', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
